### PR TITLE
better way to repeat command n times

### PR DESCRIPTION
**Pull request by tom-huntington**
Thanks for the code!

### CODE REVIEW

**Comment by tom-huntington** [comment]
Woops I guess `seq` is not posix

**Comment by jumps-are-op** [comment]
*POSIX moment*

**Comment by tom-huntington** [comment]
How did you learn shell? Just by playing around? It seems like reading your code is the best way to learn shell.

**Comment by jumps-are-op** [comment]
Usually throw writing shell scripts for strictly POSIX shells (like dash) and reading POSIX man pages.

Don't use my code as the "golden standard", I have written a lot of bad code and I'm not proud of it.

Believe it or not, I actually started learning programming in Windows™ Batch before switching to Linux 3 years ago.

**Comment by tom-huntington** [comment]
Maybe you'd like this editor https://kakoune.org/
Vim is intended to be scripted in vimscript
Neovim in Lua
Kakoune in posix shell (although you can configure bash too)

**Comment by jumps-are-op** [comment]
Well, not really. I daily drive [NextVI](https://github.com/kyx0r/nextvi), which is like the VI editor but in C and configured using patches, just like [suckless.org](https://suckless.org) software.

**Comment by tom-huntington** [comment]
The idea of kakoune is you can dynamically configure it by calling editor builtins with the output of shell commands
```
// open file computed from a shell script
// for example: open file matching a prefix, instead of having to provide the complete file name
:e %sh{ find . -maxdepth 1 -type f -name "${1}*" | head -n 1 }
// you can then alias this as its own command i.e.
:eauto README
// https://github.com/mawww/kakoune/wiki/Shell-scripting
```

People write some advanced shell plugins with this https://kakoune.org/plugins.html

Maybe you'd like to steal this idea for your vi editor?

**Pull request closed without merging**
